#!/usr/bin/env python3
"""
Generated by AI, PR's welcome to replace it.

Generate Wayland protocol D bindings from a JSON file.

Invokes the wayland-d scanner for each protocol, optionally patching in
extra imports afterwards. Skips protocols whose output file already exists
unless --force is passed.

Usage:
    python3 generate_protocols.py protocols.json
    python3 generate_protocols.py protocols.json --force
    python3 generate_protocols.py protocols.json --base-dir /path/to/core
"""

import json
import argparse
import subprocess
import sys
from pathlib import Path
from typing import List, Optional


# =============================================================================
# Protocol Entry
# =============================================================================

class Protocol:
    """A single protocol binding to generate."""

    def __init__(self, data: dict, base_dir: Path):
        self.xml            = base_dir / data['xml']
        self.module         = data['module']
        self.output         = base_dir / data['output']
        self.extra_imports: List[str] = data.get('extra_imports', [])

    def name(self) -> str:
        """Friendly display name derived from the output filename."""
        return self.output.stem


# =============================================================================
# Generator
# =============================================================================

def find_scanner(manifest_path: Path) -> List[str]:
    selections = manifest_path.parent.parent / 'dub.selections.json'
    if selections.exists():
        try:
            data = json.loads(selections.read_text())
            entry = data.get('versions', {}).get('wayland')
            if isinstance(entry, dict) and 'path' in entry:
                binary = (selections.parent / entry['path'] / 'scanner' / 'wayland_scanner').resolve()
                if binary.is_file():
                    return [str(binary)]
        except Exception:
            pass
    return ['dub', 'run', 'wayland:scanner', '--']


class ProtocolGenerator:
    """Runs the wayland-d scanner and applies post-processing."""

    def __init__(self, force: bool = False, scanner: Optional[List[str]] = None):
        self.force = force
        self.scanner = scanner

    def run(self, protocol: Protocol) -> bool:
        """
        Generate bindings for a single protocol.

        Returns True if generation happened, False if skipped.
        """
        if not self.force and protocol.output.exists():
            print(f'  skip  {protocol.name()} (already exists)')
            return False

        print(f'  gen   {protocol.name()}')
        self._run_scanner(protocol)

        if protocol.extra_imports:
            self._patch_imports(protocol)

        return True

    def _run_scanner(self, protocol: Protocol) -> None:
        """Invoke the wayland-d scanner to generate the binding."""
        protocol.output.parent.mkdir(parents=True, exist_ok=True)
        cmd = (self.scanner or ['dub', 'run', 'wayland:scanner', '--']) + [
            '-c', 'server',
            '-m', protocol.module,
            '-i', str(protocol.xml),
            '-o', str(protocol.output),
            '--passthrough', 'wl_callback,wl_region',
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f'ERROR: scanner failed for {protocol.name()}', file=sys.stderr)
            print(result.stderr, file=sys.stderr)
            sys.exit(result.returncode)

    def _patch_imports(self, protocol: Protocol) -> None:
        """
        Insert extra_imports before 'import wayland.server;' in the generated file.

        The scanner always emits this import; extras are injected right before it.
        """
        anchor = 'import wayland.server;'
        text = protocol.output.read_text()

        if anchor not in text:
            print(f'  warn  {protocol.name()}: anchor "{anchor}" not found, skipping import patch')
            return

        insert = '\n'.join(f'import {imp};' for imp in protocol.extra_imports)
        patched = text.replace(anchor, f'{insert}\n{anchor}', 1)
        protocol.output.write_text(patched)


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    parser = argparse.ArgumentParser(
        description='Generate Wayland protocol D bindings from a JSON manifest.'
    )
    parser.add_argument('manifest', help='Path to protocols JSON manifest')
    parser.add_argument(
        '--base-dir',
        help='Base directory for relative paths in the manifest (default: manifest directory)'
    )
    parser.add_argument(
        '--force', action='store_true',
        help='Regenerate even if output files already exist'
    )

    args = parser.parse_args()

    manifest_path = Path(args.manifest).resolve()
    base_dir = Path(args.base_dir).resolve() if args.base_dir else manifest_path.parent

    with open(manifest_path) as f:
        data = json.load(f)

    protocols = [Protocol(entry, base_dir) for entry in data['protocols']]
    scanner = find_scanner(manifest_path)
    generator = ProtocolGenerator(force=args.force, scanner=scanner)

    print(f'Generating {len(protocols)} protocol(s) from {manifest_path.name}:')
    generated = sum(1 for p in protocols if generator.run(p))
    skipped = len(protocols) - generated
    print(f'Done. {generated} generated, {skipped} skipped.')


if __name__ == '__main__':
    main()
